name: happy_wallet
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  web3dart: ^2.3.5
  modal_bottom_sheet: ^2.1.0
  freezed: ^2.1.0+1
  flutter_secure_storage: ^5.0.2
  build_runner: ^2.2.0
  flutter_bloc: ^8.0.1
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter